@FleetControl.Api_HostAddress = http://localhost:5246

GET {{FleetControl.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{FleetControl.Api_HostAddress}}/api/empresas
Content-Type: application/json

{
  "nome": "FleetControl Mineração",
  "ativo": true
}